### PR TITLE
Update transactions.md (fixed typo)

### PR DESCRIPTION
**Pull request by tsubakimoto**
I corrected typo.

### CODE REVIEW

**Comment by tsubakimoto** [comment]
Hi, @opbld30 .
I made a PR via edit link on [here](https://docs.microsoft.com/ja-jp/ef/core/saving/transactions), reference a below image.
Please teach me how to make a PR, I do.

2019-01-23_15h53_41

**Comment by tsubakimoto** [comment]
I made a PR according to this content.
https://github.com/aspnet/EntityFramework.Docs.ja-jp/blob/live/CONTRIBUTING.md#%E7%B0%A1%E5%8D%98%E3%81%AA%E4%BF%AE%E6%AD%A3%E3%82%84%E6%8F%90%E6%A1%88%E3%82%92%E8%A1%8C%E3%81%86%E6%96%B9%E6%B3%95

**Comment by v-elcou** [comment]
Hello @tsubakimoto,
Thank for your contribution. We are currently reviewing and will communicate the decision taken. 
Thanks for your time and support on this.

Kind regards,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@tsubakimoto , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Comment by tsubakimoto** [comment]
Hi, @v-radelg . Thank you for merging.

I have a question.
I created a PR [this way](https://github.com/aspnet/EntityFramework.Docs.ja-jp/blob/live/CONTRIBUTING.md#%E7%B0%A1%E5%8D%98%E3%81%AA%E4%BF%AE%E6%AD%A3%E3%82%84%E6%8F%90%E6%A1%88%E3%82%92%E8%A1%8C%E3%81%86%E6%96%B9%E6%B3%95), but had other things to do?

(Are @opbld30 and @opbld32 bot?)

**Comment by v-radelg** [comment]
Hi @tsubakimoto 

Thank you for your message.

The PR you commited was correctly created. Yes, opbld are bots, so you don't have to worry about those comments.

Microsoft C&E Localization Team

**Comment by tsubakimoto** [comment]
@v-radelg thanks.

**Pull request merged**
